name: watcha_body
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.00.0 <4.0.0"

dependencies:
  bloc: ^8.0.3
  collection: ^1.17.2
  d_chart: ^2.6.2
  dartz: ^0.10.1
  enum_to_string: ^2.0.1
  external_path: ^1.0.1
  file_picker: ^6.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  hydrated_bloc: ^9.1.2
  intl: ^0.18.1
  media_scanner: ^2.1.0
  path: ^1.8.0
  path_provider: ^2.0.11
  permission_handler: ^11.0.1
  share_plus: ^7.2.1
  sqflite: ^2.0.2

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  mockito: ^5.1.0
  mocktail: ^1.0.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
