// Mocks generated by Mockito 5.4.6 from annotations
// in watcha_body/test/data/repositories/app_backup_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:watcha_body/data/repositories/bodypicture_repository.dart'
    as _i13;
import 'package:watcha_body/data/repositories/measurement_repository.dart'
    as _i4;
import 'package:watcha_body/data/services/database_service.dart' as _i2;
import 'package:watcha_body/domain/body_picture/models/image_tag_model.dart'
    as _i15;
import 'package:watcha_body/domain/body_picture/models/save_vault_image_request.dart'
    as _i17;
import 'package:watcha_body/domain/body_picture/models/vault_image_model.dart'
    as _i16;
import 'package:watcha_body/domain/measurement/i_measurements.dart' as _i12;
import 'package:watcha_body/domain/measurement/models/measurement_entity.dart'
    as _i6;
import 'package:watcha_body/domain/measurement/models/measurement_model.dart'
    as _i9;
import 'package:watcha_body/domain/measurement/models/overview_widget_model.dart'
    as _i11;
import 'package:watcha_body/domain/measurement_target/model/measurement_target_model.dart'
    as _i7;
import 'package:watcha_body/domain/models/compare_images_model.dart' as _i18;
import 'package:watcha_body/domain/models/restore_summary.dart' as _i8;
import 'package:watcha_body/domain/models/two_dates_record_model.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabaseService_0 extends _i1.SmartFake
    implements _i2.DatabaseService {
  _FakeDatabaseService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MeasurementRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMeasurementRepository extends _i1.Mock
    implements _i4.MeasurementRepository {
  MockMeasurementRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseService get databaseService =>
      (super.noSuchMethod(
            Invocation.getter(#databaseService),
            returnValue: _FakeDatabaseService_0(
              this,
              Invocation.getter(#databaseService),
            ),
          )
          as _i2.DatabaseService);

  @override
  _i5.Future<_i3.Either<String, _i3.Unit>> createMeasurement({
    required _i6.MeasurementEntity? measurement,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createMeasurement, [], {
              #measurement: measurement,
            }),
            returnValue: _i5.Future<_i3.Either<String, _i3.Unit>>.value(
              _FakeEither_1<String, _i3.Unit>(
                this,
                Invocation.method(#createMeasurement, [], {
                  #measurement: measurement,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Either<String, _i3.Unit>>);

  @override
  _i5.Future<_i3.Either<String, _i3.Unit>> saveMeasurements({
    required List<_i6.MeasurementEntity>? measurements,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveMeasurements, [], {
              #measurements: measurements,
            }),
            returnValue: _i5.Future<_i3.Either<String, _i3.Unit>>.value(
              _FakeEither_1<String, _i3.Unit>(
                this,
                Invocation.method(#saveMeasurements, [], {
                  #measurements: measurements,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Either<String, _i3.Unit>>);

  @override
  _i5.Future<_i3.Either<String, _i4.BmiTrackingActivationResult>>
  activateBmiTracking({int? userId = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#activateBmiTracking, [], {#userId: userId}),
            returnValue:
                _i5.Future<
                  _i3.Either<String, _i4.BmiTrackingActivationResult>
                >.value(
                  _FakeEither_1<String, _i4.BmiTrackingActivationResult>(
                    this,
                    Invocation.method(#activateBmiTracking, [], {
                      #userId: userId,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<String, _i4.BmiTrackingActivationResult>>);

  @override
  _i5.Future<_i3.Either<String, _i3.Unit>> deleteAllData({String? id}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllData, [], {#id: id}),
            returnValue: _i5.Future<_i3.Either<String, _i3.Unit>>.value(
              _FakeEither_1<String, _i3.Unit>(
                this,
                Invocation.method(#deleteAllData, [], {#id: id}),
              ),
            ),
          )
          as _i5.Future<_i3.Either<String, _i3.Unit>>);

  @override
  _i5.Future<_i3.Either<String, List<_i6.MeasurementEntity>>>
  getLatestDetails() =>
      (super.noSuchMethod(
            Invocation.method(#getLatestDetails, []),
            returnValue:
                _i5.Future<
                  _i3.Either<String, List<_i6.MeasurementEntity>>
                >.value(
                  _FakeEither_1<String, List<_i6.MeasurementEntity>>(
                    this,
                    Invocation.method(#getLatestDetails, []),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<String, List<_i6.MeasurementEntity>>>);

  @override
  _i5.Future<_i3.Either<String, _i3.Unit>> updateMeasurement({
    required _i6.MeasurementEntity? measurement,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateMeasurement, [], {
              #measurement: measurement,
            }),
            returnValue: _i5.Future<_i3.Either<String, _i3.Unit>>.value(
              _FakeEither_1<String, _i3.Unit>(
                this,
                Invocation.method(#updateMeasurement, [], {
                  #measurement: measurement,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Either<String, _i3.Unit>>);

  @override
  _i5.Future<_i3.Either<String, List<_i7.MeasurementTargetModel>>>
  getNonAddedTargets() =>
      (super.noSuchMethod(
            Invocation.method(#getNonAddedTargets, []),
            returnValue:
                _i5.Future<
                  _i3.Either<String, List<_i7.MeasurementTargetModel>>
                >.value(
                  _FakeEither_1<String, List<_i7.MeasurementTargetModel>>(
                    this,
                    Invocation.method(#getNonAddedTargets, []),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<String, List<_i7.MeasurementTargetModel>>>);

  @override
  _i5.Future<_i3.Either<String, List<_i7.MeasurementTargetModel>>>
  getAllTargets() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTargets, []),
            returnValue:
                _i5.Future<
                  _i3.Either<String, List<_i7.MeasurementTargetModel>>
                >.value(
                  _FakeEither_1<String, List<_i7.MeasurementTargetModel>>(
                    this,
                    Invocation.method(#getAllTargets, []),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<String, List<_i7.MeasurementTargetModel>>>);

  @override
  _i5.Future<_i3.Either<String, _i7.MeasurementTargetModel>>
  createCustomTarget({
    required String? name,
    required String? metricCode,
    required String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createCustomTarget, [], {
              #name: name,
              #metricCode: metricCode,
              #category: category,
            }),
            returnValue:
                _i5.Future<
                  _i3.Either<String, _i7.MeasurementTargetModel>
                >.value(
                  _FakeEither_1<String, _i7.MeasurementTargetModel>(
                    this,
                    Invocation.method(#createCustomTarget, [], {
                      #name: name,
                      #metricCode: metricCode,
                      #category: category,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<String, _i7.MeasurementTargetModel>>);

  @override
  _i5.Future<_i3.Either<String, _i3.Unit>> updateCustomTarget({
    required int? id,
    required String? name,
    required String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateCustomTarget, [], {
              #id: id,
              #name: name,
              #category: category,
            }),
            returnValue: _i5.Future<_i3.Either<String, _i3.Unit>>.value(
              _FakeEither_1<String, _i3.Unit>(
                this,
                Invocation.method(#updateCustomTarget, [], {
                  #id: id,
                  #name: name,
                  #category: category,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Either<String, _i3.Unit>>);

  @override
  _i5.Future<_i3.Either<String, _i3.Unit>> deleteCustomTarget({
    required int? id,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCustomTarget, [], {#id: id}),
            returnValue: _i5.Future<_i3.Either<String, _i3.Unit>>.value(
              _FakeEither_1<String, _i3.Unit>(
                this,
                Invocation.method(#deleteCustomTarget, [], {#id: id}),
              ),
            ),
          )
          as _i5.Future<_i3.Either<String, _i3.Unit>>);

  @override
  _i5.Future<_i3.Either<String, List<_i7.MeasurementTargetModel>>>
  getCustomTargets() =>
      (super.noSuchMethod(
            Invocation.method(#getCustomTargets, []),
            returnValue:
                _i5.Future<
                  _i3.Either<String, List<_i7.MeasurementTargetModel>>
                >.value(
                  _FakeEither_1<String, List<_i7.MeasurementTargetModel>>(
                    this,
                    Invocation.method(#getCustomTargets, []),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<String, List<_i7.MeasurementTargetModel>>>);

  @override
  _i5.Future<_i3.Either<String, String>> backupDatabase() =>
      (super.noSuchMethod(
            Invocation.method(#backupDatabase, []),
            returnValue: _i5.Future<_i3.Either<String, String>>.value(
              _FakeEither_1<String, String>(
                this,
                Invocation.method(#backupDatabase, []),
              ),
            ),
          )
          as _i5.Future<_i3.Either<String, String>>);

  @override
  _i5.Future<_i3.Either<String, _i8.RestoreSummary>> restoreDatabase({
    bool? merge = false,
    required String? stringifiedDatas,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#restoreDatabase, [], {
              #merge: merge,
              #stringifiedDatas: stringifiedDatas,
            }),
            returnValue:
                _i5.Future<_i3.Either<String, _i8.RestoreSummary>>.value(
                  _FakeEither_1<String, _i8.RestoreSummary>(
                    this,
                    Invocation.method(#restoreDatabase, [], {
                      #merge: merge,
                      #stringifiedDatas: stringifiedDatas,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<String, _i8.RestoreSummary>>);

  @override
  _i5.Future<_i3.Either<String, _i3.Unit>> deleteMeasurement({
    required String? id,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMeasurement, [], {#id: id}),
            returnValue: _i5.Future<_i3.Either<String, _i3.Unit>>.value(
              _FakeEither_1<String, _i3.Unit>(
                this,
                Invocation.method(#deleteMeasurement, [], {#id: id}),
              ),
            ),
          )
          as _i5.Future<_i3.Either<String, _i3.Unit>>);

  @override
  _i5.Future<_i3.Either<String, List<_i9.MeasurementModel>>>
  getAllMeasurementsByDate({required DateTime? date}) =>
      (super.noSuchMethod(
            Invocation.method(#getAllMeasurementsByDate, [], {#date: date}),
            returnValue:
                _i5.Future<
                  _i3.Either<String, List<_i9.MeasurementModel>>
                >.value(
                  _FakeEither_1<String, List<_i9.MeasurementModel>>(
                    this,
                    Invocation.method(#getAllMeasurementsByDate, [], {
                      #date: date,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<String, List<_i9.MeasurementModel>>>);

  @override
  _i5.Future<_i3.Either<String, List<_i10.TwoDatesRecord>>>
  getAllRecordsByTwoDates({
    required DateTime? dateOne,
    required DateTime? dateTwo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllRecordsByTwoDates, [], {
              #dateOne: dateOne,
              #dateTwo: dateTwo,
            }),
            returnValue:
                _i5.Future<_i3.Either<String, List<_i10.TwoDatesRecord>>>.value(
                  _FakeEither_1<String, List<_i10.TwoDatesRecord>>(
                    this,
                    Invocation.method(#getAllRecordsByTwoDates, [], {
                      #dateOne: dateOne,
                      #dateTwo: dateTwo,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<String, List<_i10.TwoDatesRecord>>>);

  @override
  _i5.Future<_i3.Either<String, List<String>>> getAllMeasurementItems() =>
      (super.noSuchMethod(
            Invocation.method(#getAllMeasurementItems, []),
            returnValue: _i5.Future<_i3.Either<String, List<String>>>.value(
              _FakeEither_1<String, List<String>>(
                this,
                Invocation.method(#getAllMeasurementItems, []),
              ),
            ),
          )
          as _i5.Future<_i3.Either<String, List<String>>>);

  @override
  _i5.Future<_i3.Either<String, List<_i6.MeasurementEntity>>>
  getMeasurementItemDataByDateRange({
    required DateTime? startDate,
    required DateTime? endDate,
    required int? measurementItemId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMeasurementItemDataByDateRange, [], {
              #startDate: startDate,
              #endDate: endDate,
              #measurementItemId: measurementItemId,
            }),
            returnValue:
                _i5.Future<
                  _i3.Either<String, List<_i6.MeasurementEntity>>
                >.value(
                  _FakeEither_1<String, List<_i6.MeasurementEntity>>(
                    this,
                    Invocation.method(#getMeasurementItemDataByDateRange, [], {
                      #startDate: startDate,
                      #endDate: endDate,
                      #measurementItemId: measurementItemId,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<String, List<_i6.MeasurementEntity>>>);

  @override
  _i5.Future<_i3.Either<String, Map<String, List<_i9.MeasurementModel>>>>
  getLatestThreeMeasurements({int? userId = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestThreeMeasurements, [], {
              #userId: userId,
            }),
            returnValue:
                _i5.Future<
                  _i3.Either<String, Map<String, List<_i9.MeasurementModel>>>
                >.value(
                  _FakeEither_1<
                    String,
                    Map<String, List<_i9.MeasurementModel>>
                  >(
                    this,
                    Invocation.method(#getLatestThreeMeasurements, [], {
                      #userId: userId,
                    }),
                  ),
                ),
          )
          as _i5.Future<
            _i3.Either<String, Map<String, List<_i9.MeasurementModel>>>
          >);

  @override
  _i5.Future<_i3.Either<String, List<_i11.OverviewWidgetModel>>>
  getOverviewWidgetsData({int? userId = 1, int? latestLimit = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#getOverviewWidgetsData, [], {
              #userId: userId,
              #latestLimit: latestLimit,
            }),
            returnValue:
                _i5.Future<
                  _i3.Either<String, List<_i11.OverviewWidgetModel>>
                >.value(
                  _FakeEither_1<String, List<_i11.OverviewWidgetModel>>(
                    this,
                    Invocation.method(#getOverviewWidgetsData, [], {
                      #userId: userId,
                      #latestLimit: latestLimit,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<String, List<_i11.OverviewWidgetModel>>>);

  @override
  _i5.Future<_i3.Either<String, List<_i9.MeasurementModel>>>
  getMeasurementsByTarget({
    required int? targetId,
    int? userId = 1,
    _i12.MeasurementSourceFilter? sourceFilter =
        _i12.MeasurementSourceFilter.both,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMeasurementsByTarget, [], {
              #targetId: targetId,
              #userId: userId,
              #sourceFilter: sourceFilter,
            }),
            returnValue:
                _i5.Future<
                  _i3.Either<String, List<_i9.MeasurementModel>>
                >.value(
                  _FakeEither_1<String, List<_i9.MeasurementModel>>(
                    this,
                    Invocation.method(#getMeasurementsByTarget, [], {
                      #targetId: targetId,
                      #userId: userId,
                      #sourceFilter: sourceFilter,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<String, List<_i9.MeasurementModel>>>);
}

/// A class which mocks [BodyPictureRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBodyPictureRepository extends _i1.Mock
    implements _i13.BodyPictureRepository {
  MockBodyPictureRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseService get databaseService =>
      (super.noSuchMethod(
            Invocation.getter(#databaseService),
            returnValue: _FakeDatabaseService_0(
              this,
              Invocation.getter(#databaseService),
            ),
          )
          as _i2.DatabaseService);

  @override
  String get imagesFolderPath =>
      (super.noSuchMethod(
            Invocation.getter(#imagesFolderPath),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#imagesFolderPath),
            ),
          )
          as String);

  @override
  String get thumbnailsFolderPath =>
      (super.noSuchMethod(
            Invocation.getter(#thumbnailsFolderPath),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#thumbnailsFolderPath),
            ),
          )
          as String);

  @override
  _i5.Future<_i3.Either<String, _i15.ImageTagModel>> addTag(String? tag) =>
      (super.noSuchMethod(
            Invocation.method(#addTag, [tag]),
            returnValue:
                _i5.Future<_i3.Either<String, _i15.ImageTagModel>>.value(
                  _FakeEither_1<String, _i15.ImageTagModel>(
                    this,
                    Invocation.method(#addTag, [tag]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<String, _i15.ImageTagModel>>);

  @override
  _i5.Future<_i3.Either<String, _i15.ImageTagModel>> getTagById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTagById, [id]),
            returnValue:
                _i5.Future<_i3.Either<String, _i15.ImageTagModel>>.value(
                  _FakeEither_1<String, _i15.ImageTagModel>(
                    this,
                    Invocation.method(#getTagById, [id]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<String, _i15.ImageTagModel>>);

  @override
  _i5.Future<_i3.Either<String, _i3.Unit>> deleteAllBodyPictures() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllBodyPictures, []),
            returnValue: _i5.Future<_i3.Either<String, _i3.Unit>>.value(
              _FakeEither_1<String, _i3.Unit>(
                this,
                Invocation.method(#deleteAllBodyPictures, []),
              ),
            ),
          )
          as _i5.Future<_i3.Either<String, _i3.Unit>>);

  @override
  _i5.Future<_i3.Either<String, void>> deleteBodyPicture(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBodyPicture, [id]),
            returnValue: _i5.Future<_i3.Either<String, void>>.value(
              _FakeEither_1<String, void>(
                this,
                Invocation.method(#deleteBodyPicture, [id]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<String, void>>);

  @override
  _i5.Future<_i3.Either<String, List<_i16.VaultImageModel>>>
  getAllBodyPictures() =>
      (super.noSuchMethod(
            Invocation.method(#getAllBodyPictures, []),
            returnValue:
                _i5.Future<
                  _i3.Either<String, List<_i16.VaultImageModel>>
                >.value(
                  _FakeEither_1<String, List<_i16.VaultImageModel>>(
                    this,
                    Invocation.method(#getAllBodyPictures, []),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<String, List<_i16.VaultImageModel>>>);

  @override
  _i5.Future<_i3.Either<String, List<_i15.ImageTagModel>>> getAllTags() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTags, []),
            returnValue:
                _i5.Future<_i3.Either<String, List<_i15.ImageTagModel>>>.value(
                  _FakeEither_1<String, List<_i15.ImageTagModel>>(
                    this,
                    Invocation.method(#getAllTags, []),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<String, List<_i15.ImageTagModel>>>);

  @override
  _i5.Future<_i3.Either<String, _i16.VaultImageModel>> getBodyPictureById(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBodyPictureById, [id]),
            returnValue:
                _i5.Future<_i3.Either<String, _i16.VaultImageModel>>.value(
                  _FakeEither_1<String, _i16.VaultImageModel>(
                    this,
                    Invocation.method(#getBodyPictureById, [id]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<String, _i16.VaultImageModel>>);

  @override
  _i5.Future<_i3.Either<String, List<_i16.VaultImageModel>>>
  getBodyPicturesByTag(String? tag) =>
      (super.noSuchMethod(
            Invocation.method(#getBodyPicturesByTag, [tag]),
            returnValue:
                _i5.Future<
                  _i3.Either<String, List<_i16.VaultImageModel>>
                >.value(
                  _FakeEither_1<String, List<_i16.VaultImageModel>>(
                    this,
                    Invocation.method(#getBodyPicturesByTag, [tag]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<String, List<_i16.VaultImageModel>>>);

  @override
  _i5.Future<_i3.Either<String, void>> removeTag(String? tag) =>
      (super.noSuchMethod(
            Invocation.method(#removeTag, [tag]),
            returnValue: _i5.Future<_i3.Either<String, void>>.value(
              _FakeEither_1<String, void>(
                this,
                Invocation.method(#removeTag, [tag]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<String, void>>);

  @override
  _i5.Future<_i3.Either<String, _i16.VaultImageModel>> saveBodyPicture(
    _i17.SaveVaultImageRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveBodyPicture, [request]),
            returnValue:
                _i5.Future<_i3.Either<String, _i16.VaultImageModel>>.value(
                  _FakeEither_1<String, _i16.VaultImageModel>(
                    this,
                    Invocation.method(#saveBodyPicture, [request]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<String, _i16.VaultImageModel>>);

  @override
  _i5.Future<_i3.Either<String, _i16.VaultImageModel>> updateBodyPicture(
    _i16.VaultImageModel? bodyPicture,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBodyPicture, [bodyPicture]),
            returnValue:
                _i5.Future<_i3.Either<String, _i16.VaultImageModel>>.value(
                  _FakeEither_1<String, _i16.VaultImageModel>(
                    this,
                    Invocation.method(#updateBodyPicture, [bodyPicture]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<String, _i16.VaultImageModel>>);

  @override
  _i5.Future<_i3.Either<String, _i18.CompareImagesModel>>
  getBodyPicturesByTagAndTwoDate({
    required int? tag,
    required DateTime? firstdate,
    required DateTime? seconddate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBodyPicturesByTagAndTwoDate, [], {
              #tag: tag,
              #firstdate: firstdate,
              #seconddate: seconddate,
            }),
            returnValue:
                _i5.Future<_i3.Either<String, _i18.CompareImagesModel>>.value(
                  _FakeEither_1<String, _i18.CompareImagesModel>(
                    this,
                    Invocation.method(#getBodyPicturesByTagAndTwoDate, [], {
                      #tag: tag,
                      #firstdate: firstdate,
                      #seconddate: seconddate,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<String, _i18.CompareImagesModel>>);

  @override
  _i5.Future<_i3.Either<String, String>> backupPhotosToZip() =>
      (super.noSuchMethod(
            Invocation.method(#backupPhotosToZip, []),
            returnValue: _i5.Future<_i3.Either<String, String>>.value(
              _FakeEither_1<String, String>(
                this,
                Invocation.method(#backupPhotosToZip, []),
              ),
            ),
          )
          as _i5.Future<_i3.Either<String, String>>);

  @override
  _i5.Future<_i3.Either<String, String>> createPicturesBackupArchive({
    required String? outputZipPath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPicturesBackupArchive, [], {
              #outputZipPath: outputZipPath,
            }),
            returnValue: _i5.Future<_i3.Either<String, String>>.value(
              _FakeEither_1<String, String>(
                this,
                Invocation.method(#createPicturesBackupArchive, [], {
                  #outputZipPath: outputZipPath,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Either<String, String>>);

  @override
  _i5.Future<_i3.Either<String, String>> createPicturesOnlyArchive({
    required String? outputZipPath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPicturesOnlyArchive, [], {
              #outputZipPath: outputZipPath,
            }),
            returnValue: _i5.Future<_i3.Either<String, String>>.value(
              _FakeEither_1<String, String>(
                this,
                Invocation.method(#createPicturesOnlyArchive, [], {
                  #outputZipPath: outputZipPath,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Either<String, String>>);

  @override
  _i5.Future<_i3.Either<String, _i8.RestoreSummary>> restorePhotosFromZip({
    required String? zipPath,
    bool? merge = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#restorePhotosFromZip, [], {
              #zipPath: zipPath,
              #merge: merge,
            }),
            returnValue:
                _i5.Future<_i3.Either<String, _i8.RestoreSummary>>.value(
                  _FakeEither_1<String, _i8.RestoreSummary>(
                    this,
                    Invocation.method(#restorePhotosFromZip, [], {
                      #zipPath: zipPath,
                      #merge: merge,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<String, _i8.RestoreSummary>>);

  @override
  _i5.Future<_i3.Either<String, List<String>>> getAllMuscleGroups() =>
      (super.noSuchMethod(
            Invocation.method(#getAllMuscleGroups, []),
            returnValue: _i5.Future<_i3.Either<String, List<String>>>.value(
              _FakeEither_1<String, List<String>>(
                this,
                Invocation.method(#getAllMuscleGroups, []),
              ),
            ),
          )
          as _i5.Future<_i3.Either<String, List<String>>>);
}
