// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.32.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// AES-256 has 256-bit keys
/// we need an encryption key
Future<Uint8List> makeKey({dynamic hint}) =>
    RustLib.instance.api.makeKey(hint: hint);

Future<Uint8List> encrypt(
        {required List<int> key, required List<int> data, dynamic hint}) =>
    RustLib.instance.api.encrypt(key: key, data: data, hint: hint);

Future<Uint8List> decrypt(
        {required List<int> key, required List<int> data, dynamic hint}) =>
    RustLib.instance.api.decrypt(key: key, data: data, hint: hint);
