// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.32.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// AES-256 has 256-bit keys
/// we need an encryption key
Future<Uint8List> generateRandomNonce({dynamic hint}) =>
    RustLib.instance.api.generateRandomNonce(hint: hint);

Future<Uint8List> encryptWithNonce(
        {required List<int> password,
        required List<int> nonce,
        required List<int> data,
        dynamic hint}) =>
    RustLib.instance.api.encryptWithNonce(
        password: password, nonce: nonce, data: data, hint: hint);

Future<Uint8List> decryptWithNonce(
        {required List<int> password,
        required List<int> nonce,
        required List<int> data,
        dynamic hint}) =>
    RustLib.instance.api.decryptWithNonce(
        password: password, nonce: nonce, data: data, hint: hint);
