// Mocks generated by Mockito 5.4.6 from annotations
// in watcha_body/test/presentation/backup_restore_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:watcha_body/data/repositories/app_backup_repository.dart'
    as _i5;
import 'package:watcha_body/data/repositories/bodypicture_repository.dart'
    as _i3;
import 'package:watcha_body/data/repositories/measurement_repository.dart'
    as _i2;
import 'package:watcha_body/domain/models/restore_summary.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMeasurementRepository_0 extends _i1.SmartFake
    implements _i2.MeasurementRepository {
  _FakeMeasurementRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBodyPictureRepository_1 extends _i1.SmartFake
    implements _i3.BodyPictureRepository {
  _FakeBodyPictureRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppBackupRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppBackupRepository extends _i1.Mock
    implements _i5.AppBackupRepository {
  MockAppBackupRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MeasurementRepository get measurementRepository =>
      (super.noSuchMethod(
            Invocation.getter(#measurementRepository),
            returnValue: _FakeMeasurementRepository_0(
              this,
              Invocation.getter(#measurementRepository),
            ),
          )
          as _i2.MeasurementRepository);

  @override
  _i3.BodyPictureRepository get bodyPictureRepository =>
      (super.noSuchMethod(
            Invocation.getter(#bodyPictureRepository),
            returnValue: _FakeBodyPictureRepository_1(
              this,
              Invocation.getter(#bodyPictureRepository),
            ),
          )
          as _i3.BodyPictureRepository);

  @override
  _i6.Future<_i4.Either<String, String>> backupDatabase() =>
      (super.noSuchMethod(
            Invocation.method(#backupDatabase, []),
            returnValue: _i6.Future<_i4.Either<String, String>>.value(
              _FakeEither_2<String, String>(
                this,
                Invocation.method(#backupDatabase, []),
              ),
            ),
          )
          as _i6.Future<_i4.Either<String, String>>);

  @override
  _i6.Future<_i4.Either<String, _i7.RestoreSummary>> restoreDatabase({
    bool? merge = false,
    required String? stringifiedDatas,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#restoreDatabase, [], {
              #merge: merge,
              #stringifiedDatas: stringifiedDatas,
            }),
            returnValue:
                _i6.Future<_i4.Either<String, _i7.RestoreSummary>>.value(
                  _FakeEither_2<String, _i7.RestoreSummary>(
                    this,
                    Invocation.method(#restoreDatabase, [], {
                      #merge: merge,
                      #stringifiedDatas: stringifiedDatas,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i4.Either<String, _i7.RestoreSummary>>);

  @override
  _i6.Future<_i4.Either<String, String>> backupFullApp({
    bool? storeExternally = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#backupFullApp, [], {
              #storeExternally: storeExternally,
            }),
            returnValue: _i6.Future<_i4.Either<String, String>>.value(
              _FakeEither_2<String, String>(
                this,
                Invocation.method(#backupFullApp, [], {
                  #storeExternally: storeExternally,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.Either<String, String>>);

  @override
  _i6.Future<_i4.Either<String, String>> backupPicturesOnly({
    bool? storeExternally = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#backupPicturesOnly, [], {
              #storeExternally: storeExternally,
            }),
            returnValue: _i6.Future<_i4.Either<String, String>>.value(
              _FakeEither_2<String, String>(
                this,
                Invocation.method(#backupPicturesOnly, [], {
                  #storeExternally: storeExternally,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.Either<String, String>>);

  @override
  _i6.Future<_i4.Either<String, String>> exportMeasurementsCsv({
    bool? storeExternally = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#exportMeasurementsCsv, [], {
              #storeExternally: storeExternally,
            }),
            returnValue: _i6.Future<_i4.Either<String, String>>.value(
              _FakeEither_2<String, String>(
                this,
                Invocation.method(#exportMeasurementsCsv, [], {
                  #storeExternally: storeExternally,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.Either<String, String>>);

  @override
  _i6.Future<_i4.Either<String, String>> exportMeasurementsPdf({
    bool? storeExternally = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#exportMeasurementsPdf, [], {
              #storeExternally: storeExternally,
            }),
            returnValue: _i6.Future<_i4.Either<String, String>>.value(
              _FakeEither_2<String, String>(
                this,
                Invocation.method(#exportMeasurementsPdf, [], {
                  #storeExternally: storeExternally,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.Either<String, String>>);

  @override
  _i6.Future<_i4.Either<String, _i7.RestoreSummary>> restoreFullApp({
    required String? backupPath,
    bool? merge = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#restoreFullApp, [], {
              #backupPath: backupPath,
              #merge: merge,
            }),
            returnValue:
                _i6.Future<_i4.Either<String, _i7.RestoreSummary>>.value(
                  _FakeEither_2<String, _i7.RestoreSummary>(
                    this,
                    Invocation.method(#restoreFullApp, [], {
                      #backupPath: backupPath,
                      #merge: merge,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i4.Either<String, _i7.RestoreSummary>>);

  @override
  _i6.Future<_i4.Either<String, String>> identifyBackupType({
    required String? backupPath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#identifyBackupType, [], {
              #backupPath: backupPath,
            }),
            returnValue: _i6.Future<_i4.Either<String, String>>.value(
              _FakeEither_2<String, String>(
                this,
                Invocation.method(#identifyBackupType, [], {
                  #backupPath: backupPath,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.Either<String, String>>);
}
