name: watcha_body

on: 
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.16.0
